### ISSUE TITLE
Build a GUI

### ISSUE THREAD

**Issue by finlaywashere** [FRC2706/NetworkTablesMonitor#5]
It needs a GUI to work nicely

**Comment by virtuald** [comment]
Just out of curiosity, have you considered using OutlineViewer instead of reinventing the wheel?

**Comment by finlaywashere** [comment]
Yes, but mine is better. Mine supports being a server as well as connecting to clients and it can also run add-ons

**Comment by virtuald** [comment]
Have you used it? OutlineViewer can be a server also.

It seems that if yours is better (and not particularly different), perhaps it would make sense to make contributions to OutlineViewer so the FRC community can more easily benefit from your work. :+1:

**Comment by ounsworth** [comment]
[Mentor] Thank you @virtuald . The better answer is that this is Finlay's first year on the team and he wanted to implement it from scratch for his own learning; the rest of the team does indeed use Outline Viewer. 

We will encourage Finlay in the future to spend his effort using and contributing to existing open source projects rather than reinventing the wheel 🙂

**Comment by virtuald** [comment]
Haha, no worries. I didn't mean to discourage or demean the effort that was put into this project, and if it came off that way I apologize! There can be a lot of value in reinventing the wheel and learning to do it yourself, just as long as you're aware you're doing so! :)

I'm sure they learned a ton from working on this project, good luck in the future!
